### PR TITLE
fix: adds systray kill on health kill api

### PR DESCRIPTION
**Pull request by vivekbharatha**
Issue: https://github.com/flybywiresim/simbridge/issues/15#issuecomment-1231171460

Changes:
- Adds systray service kill on health kill api

### CODE REVIEW

**Comment by vivekbharatha** [comment]
@Lucky38i , could you please review this?

**Review by Lucky38i — COMMENTED** [review]
I'm not sure I like this solution as it creates added coupling further down the line, for example when Sven's get around to gracefully shutting down his worker threads. I'm working on a solution #43 that will emit a shutdown even from within a service.

**Comment by vivekbharatha** [comment]
New PR looks great, will go ahead with that then

**Comment by Lucky38i** [comment]
Closing this in favor of #43

**Pull request closed without merging**
