### PR TITLE
feat: add keyboard shortcut support for the mcdu remote display in browser mode

### PR DESCRIPTION
**Pull request by ozgend**
docs pr ref: https://github.com/flybywiresim/docs/pull/887

---

this pr introduces keyboard shortcuts to the remote mcdu display on the browser via js keyEvents.

### keyboard - mcdu key mapping

| keyboard code        | mcdu key  |
| -------------------- | --------- |
| `F1`-`F6`            | LSK1-LSK6 |
| `F7`-`F12`           | RSK1-RSK6 |
| `A-Z`                | A-Z       |
| `0-9`, Digit, Numpad | 0-9       |
| `Tab`                | DIR       |
| `Insert`             | PROG      |
| `Home`               | PERF      |
| `PageUp`             | INIT      |
| `Enter`              | DATA      |
| `NumpadEnter`        | DATA      |
| `Delete`             | FPLN      |
| `End`                | RAD       |
| `PageDown`           | FUEL      |
| `Escape`             | MENU      |
| `ShiftLeft`          | AIRPORT   |
| `ArrowLeft`          | PREVPAGE  |
| `ArrowRight`         | NEXTPAGE  |
| `ArrowUp`            | UP        |
| `ArrowDown`          | DOWN      |
| `Backspace`          | CLR       |
| `Space`              | SP        |
| `Period`             | DOT       |
| `Slash`              | DIV       |
| `Minus`              | PLUSMINUS |
| `NumpadSubtract`     | PLUSMINUS |
| `NumpadAdd`          | PLUSMINUS |
| `NumpadDecimal`      | DOT       |
| `NumpadDivide`       | DIV       |
| `NumpadMultiply`     | OVFY      |

### CODE REVIEW

**Comment by Lucky38i** [comment]
Is there documentation for this? @ozgend

**Comment by ozgend** [comment]
> Is there documentation for this? @ozgend 

honestly, i could not find a place for mcdu ui documentation on this repo; so i only described the introduced keymap in the pr description.

i can add the keymap documentation if i'm pointed to right/proper place

**Comment by Lucky38i** [comment]
> > Is there documentation for this? @ozgend
> 
> honestly, i could not find a place for mcdu ui documentation on this repo; so i only described the introduced keymap in the pr description.
> 
> i can add the keymap documentation if i'm pointed to right/proper place

Hey, you can find our documentation here: https://github.com/flybywiresim/docs. Our docs are generated MkDocs using python. You can refer to these set of file https://github.com/flybywiresim/docs/tree/primary/docs/simbridge/simbridge-feature-guides/remote-displays for editing the documentation relating to the remote display. Feel free to ping Valastiri on the Discord for some more guidance about more intricate editing but it's fairly simple. When you reference this PR in your PR for the docs, and it's approved, I'll merge this PR and deploy it.

**Comment by Valastiri** [comment]
@Lucky38i docs are ready

**Comment by auroraisluna** [comment]
A quick idea: Perhaps also we can add some icon or button that shows a little question mark button or a keyboard icon that when clicked shows the user the available keybinds?

**Comment by ozgend** [comment]
> A quick idea: Perhaps also we can add some icon or button that shows a little question mark button or a keyboard icon that when clicked shows the user the available keybinds?

i thought the same, but i did not want to bloat and complicate the ui itself.  all the guide related to the mcdu is already on the [official documentation page](https://docs.flybywiresim.com/simbridge/simbridge-feature-guides/remote-displays/remote-mcdu/) and this feature's documentation [will be like in this preview](https://docs-git-fork-ozgend-doc-feature-mcdu-keymap-flybywire.vercel.app/simbridge/simbridge-feature-guides/remote-displays/remote-mcdu/#keyboard-mapping).

**Review by Lucky38i — APPROVED** [review]

**Pull request merged**
