### PR TITLE
Systray graceful kill

### PR DESCRIPTION
**Pull request by vivekbharatha**
Changes:
- Moved systray logic to dedicated utilities service
- Handling graceful kill on shutdown listener - Ref: https://github.com/flybywiresim/simbridge/pull/38
- This PR consists of above [mentioned pr](https://github.com/flybywiresim/simbridge/pull/38) changes too

Issue Ref: https://github.com/flybywiresim/simbridge/issues/15

### CODE REVIEW

**Comment by vivekbharatha** [comment]
@Lucky38i could you please review this?

**Review by Lucky38i — COMMENTED** [review]
This is pretty awesome, thanks for getting around to it. I'll merge once I test it locally

**Review by Lucky38i — APPROVED** [review]
works great and no more lingering systems tray icon :) great work

**Comment by vivekbharatha** [comment]
Thank you :) , will be dedicated more to this organization 💯

**Pull request merged**
